version: '3.9'

services:
    
    postgresdb:
        image: postgres:latest
        ports:
            - 5555:5432
        restart: on-failure
        volumes:
            - ./scripts/db:/docker-entrypoint-initdb.d        
            - ./postgres-data:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            PGDATA: "/var/lib/postgresql/data/pgdata"
            
    cache:
        image: redis:7.0-alpine
        restart: on-failure
        ports:
            - '6379:6379'
        environment:
            - ALLOW_EMPTY_PASSWORD=yes
        volumes: 
            - ./redis-data:/data

    auth-service:
        build:
            context: ./
            dockerfile: ./server/AuthService/Dockerfile
        ports:
            - 9004:80
        restart: on-failure
        depends_on:
            - postgresdb

    process-quest-service:
        build:
            context: ./
            dockerfile: ./server/ProcessQuestService/Dockerfile
        ports:
            - 9007:80
        restart: on-failure
        depends_on:
            - cache   

    generate-quest-service:
        build:
            context: ./
            dockerfile: ./server/GenerateQuestsService/Dockerfile
        ports:
            - 9005:80
        restart: on-failure
        depends_on:
            - postgresdb        
    
    quest-core:
        build:
            context: ./
            dockerfile: ./server/QuestCore/Dockerfile
        ports:
            - 9003:80
        restart: on-failure
        depends_on:
            - postgresdb

    prometheus:
        # Use the official Prometheus image
        image: prom/prometheus
        container_name: prometheus
        # Expose ports for Prometheus
        ports:
            - "9090:9090"
        # Mount the local Prometheus configuration file
        volumes:
            - ./prometheus.yml:/etc/prometheus/prometheus.yml
            - prometheus_data:/prometheus
        # Command to start Prometheus with the specified configuration file
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'
            - '--storage.tsdb.path=/prometheus'
            - '--web.console.libraries=/usr/share/prometheus/console_libraries'
            - '--web.console.templates=/usr/share/prometheus/consoles'
        
    # Service for Grafana
    grafana:
        container_name: grafana
        # Use the official Grafana image
        image: grafana/grafana
        depends_on:
            - prometheus
        # Set environment variables for Grafana
        environment:
            - GF_SECURITY_ADMIN_PASSWORD=admin
            - GF_SECURITY_ADMIN_USER=admin
        restart: unless-stopped
        # Expose ports for Grafana
        ports:
            - "3000:3000"
        # Mount a volume for persistent data storage
        volumes:
            - grafana_storage:/var/lib/grafana
            - ./grafana/provisioning/:/etc/grafana/provisioning/
        env_file:
            - ./grafana/config.monitoring
    
    node-exporter:
        image: prom/node-exporter
        container_name: node-exporter
        volumes:
            - /proc:/host/proc:ro
            - /sys:/host/sys:ro
        command: 
            - '--path.procfs=/host/proc' 
            - '--path.sysfs=/host/sys'
            - --collector.filesystem.ignored-mount-points
            - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
        ports:
            - 9100:9100
        restart: always


volumes:
    postgresdb:
    cache:
    prometheus_data: {}
    grafana_storage: {}

networks:
  default: